import { useContext, useLayoutEffect, useState } from 'react'
import { View, StyleSheet } from 'react-native'

import GoalForm from '../components/ManageGoal/GoalForm'
import ErrorOverlay from '../components/UI/ErrorOverLay'
import IconButton from '../components/UI/IconButton'
import LoadingOverlay from '../components/UI/LoadingOverlay'
import { GlobalStyles } from '../constants/styles'
import { GoalsContext } from '../store/goals-context'
import { storeGoal, updateGoal, deleteGoal } from '../util/http'

function ManageGoal({route, navigation}) {
    const [isSubmitting, setIsSubmitting] = useState(false)
    const [error, setError] = useState() // undefined state as theres no error initially

    const goalsCtx = useContext(GoalsContext)

    const editedGoalId = route.params?.goalId // goalId as stated in GoalItem Component, params? to determine retreving existing goal or adding new goal
    const isEditing = !!editedGoalId // !! is to convert a value into boolean, falsy into false or truthy into true

    const selectedGoal = goalsCtx.goals.find(
        (goal) => goal.id === editedGoalId) // selecting goal to prefill form for editing

    useLayoutEffect(() => { // useEffect to prevent flickering of old to new content
        navigation.setOptions({ // method to set values like title of screen
            title: isEditing ? 'Edit Goal' : 'Add Goal' // turnery to set dynamic title of screen
        })
    }, [navigation, isEditing]) // dependecies of navigation prop and isEditing helper constant

    async function deleteGoalHandler() {
        setIsSubmitting(true)
        try {
            await deleteGoal(editedGoalId)
            goalsCtx.deleteGoal(editedGoalId) // wont execute if fail to delete
            navigation.goBack()
        } catch (error) {
            setError('Could not delete goal - please try again later!')
            setIsSubmitting(false) // set to false here to prevent showing LoadingOverlay when there is an error
        }
    }

    function cancelHandler() {
        navigation.goBack()
    }

    async function confirmHandler(goalData) {
        setIsSubmitting(true)
        try {
            if (isEditing) {
                goalsCtx.updateGoal(editedGoalId, goalData)
                await updateGoal(editedGoalId, goalData)
            } else {
                const id = await storeGoal(goalData) // will get back id from storeGoal function from http.js
                goalsCtx.addGoal({ ...goalData, id: id }) // passing id field generated by firebase into goalData object
            }
            navigation.goBack()
        } catch (error) {
            setError('Could not save data - please try again later!')
            setIsSubmitting(false) // prevents LoadingOverlay spinner when theres an error
        }
    }

    if (error && !isSubmitting) {
        return <ErrorOverlay message={error} />
    }

    if (isSubmitting) {
        return <LoadingOverlay />
    }

    return (
        <View style={styles.container}>
            <GoalForm
                submitButtonLabel={isEditing ? 'Update' : 'Add'}
                onSubmit={confirmHandler} 
                onCancel={cancelHandler}
                defaultValues={selectedGoal}
            />
            {isEditing && (
                <View style={styles.deleteContainer}>
                    <IconButton 
                        icon="trash" 
                        color={GlobalStyles.colors.error500} 
                        size={36} 
                        onPress={deleteGoalHandler} 
                    />
                </View>
            )}           
        </View>
    )
}

export default ManageGoal

const styles = StyleSheet.create({
    container:{
        flex: 1,
        padding: 24,
        backgroundColor: GlobalStyles.colors.primary800    
    },
    deleteContainer: {
        marginTop: 16,
        paddingTop: 8,
        borderTopWidth: 2,
        borderTopColor: GlobalStyles.colors.primary200,
        alignItems: 'center'
    }
})